### ISSUE TITLE
sitemesh3 not decorating error pages

### ISSUE THREAD

**Issue by atomi** [sitemesh/sitemesh3#25]
if you set an error-page element in web.xml sitemesh3 won't decorate that file.

<dispatcher>ERROR</dispatcher> in the filter-mapping does nothing.
Hopefully someone can confirm this as well - just in case I might have missed something.

**Comment by m4wayne** [comment]
遇到同样的问题，help

**Comment by flopma** [comment]
Hi,

I cannot confirm this work. Actually, the ERROR dispatcher is needed because in my case Tomcat 8.0.43 will handle error page with a ERROR dispatcher (for error pages defined in the web.xml).

But when we arrive into `org.sitemesh.webapp.contentfilter.BasicSelector.filterAlreadyAppliedForRequest(HttpServletRequest)` from `org.sitemesh.webapp.contentfilter.ContentBufferingFilter.doFilter(ServletRequest, ServletResponse, FilterChain)`, the method will return `true` because the request has already been through the SiteMesh filter. This will make SiteMesh filter to skip decoration of the error page.

So I don't get how this can work. For the me bug is still there.

Can someone confirm or invalidate?

Thx

**Comment by flopma** [comment]
I had to create a new selector extending the BasicSelector and override this method so SiteMesh would work nicely with Spring Security and Spring MVC since I did not put Sitemesh as the first Filter, I prefer Spring Security filters to be the 1st.

```java
    @Override
    protected boolean filterAlreadyAppliedForRequest(HttpServletRequest request) {
      if (request.getDispatcherType().equals(DispatcherType.ERROR)) {
        LOG.debug("Currently in a ERROR dispatcher - preventing SiteMesh from skipping decoration");
        return false;
      }

      return super.filterAlreadyAppliedForRequest(request);
    }
```

**Comment by ebourg** [comment]
I tried patching `BasicSelector` with the change suggested by @flopma but this resulted in an infinite loop:

    java.lang.StackOverflowError
        at javax.servlet.ServletResponseWrapper.setContentType(ServletResponseWrapper.java:138)
        at org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.setContentType(HttpServletResponseBuffer.java:158)
        at javax.servlet.ServletResponseWrapper.setContentType(ServletResponseWrapper.java:138)
        at org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.setContentType(HttpServletResponseBuffer.java:158)
        at javax.servlet.ServletResponseWrapper.setContentType(ServletResponseWrapper.java:138)
        at org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.setContentType(HttpServletResponseBuffer.java:158)
        at javax.servlet.ServletResponseWrapper.setContentType(ServletResponseWrapper.java:138)
        at org.sitemesh.webapp.contentfilter.HttpServletResponseBuffer.setContentType(HttpServletResponseBuffer.java:158)

I've modified the logic to use an "already applied" flag specific to the ERROR type:

    protected boolean filterAlreadyAppliedForRequest(HttpServletRequest request) {
        if (request.getDispatcherType().equals(DispatcherType.ERROR)) {
            if (Boolean.TRUE.equals(request.getAttribute(ALREADY_APPLIED_KEY + ".ERROR"))) {
                return true;
            } else {
                request.setAttribute(ALREADY_APPLIED_KEY + ".ERROR", true);
                return false;
            }
        }

Now the error pages are properly decorated (and the REQUEST type is still handled by the Sitemesh filter).
