### ISSUE TITLE
sitemesh 3 support load decorator file from classpath?

### ISSUE THREAD

**Issue by linux-china** [sitemesh/sitemesh3#72]
Now I am using spring boot, and no WEB-INF directory in fact.  I put the decorator files under resources/templates/ directory.  Can I use following code in the sitemesh3.xml?
         
                <mapping decorator="classpath:templates/layout.html"/>
Or any idea to implement such feature?

**Comment by codeconsole** [comment]
Were you able to figure out a solution?

**Comment by linux-china** [comment]
@codeconsole  please put the layout.html in resources/static.     https://github.com/linux-china/mail-catcher 
![Uploading Snip20150515_10.png…]()

**Comment by chenjiangtao** [comment]
You do me a big favour!!

**Comment by Darkvater** [comment]
This is not a solution. It means that your template is available as a static resource to anyone who requests the template by name (unless we write something specific that blocks these files). Decorator files should not be publicly available. 
Hence sitemesh3 is completely broken and won't work when used in an embedded webserver environment because it relies on the servlet forwarding and processing the decorator as any other resource.
